In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [2]:
diabetes_dataset = pd.read_csv('diabetes.csv')

In [3]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
diabetes_dataset.shape

(768, 9)

In [5]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
diabetes_dataset['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [7]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [8]:
#Seprate data and labels
x = diabetes_dataset.drop(columns=['Outcome'],axis=1)
y = diabetes_dataset['Outcome']

In [9]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [10]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [11]:
# diabetes_dataset.plot(kind='scatter',x='Outcome',y='Glucose')
# diabetes_dataset.plot(kind='scatter',x='Outcome',y='Insulin',color='red')
# diabetes_dataset.plot(kind='scatter',x='Outcome',y='BloodPressure',color='green')
# # diabetes_dataset.plot(kind='scatter',x='Outcome',y='Age',color='red')

In [12]:
type(diabetes_dataset)

pandas.core.frame.DataFrame

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(x)

StandardScaler()

In [15]:
standardize_data = scaler.transform(x)

In [16]:
standardize_data[0:10]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415],
       [-0.84488505, -0.99820778, -0.16054575,  0.15453319,  0.12330164,
        -0.49404308, -0.92076261, -1.04154944],
       [-1.14185152,  0.5040552 , -1.50468724,  0.90726993,  0.76583594,
         1.4097456 ,  5.4849091 , -0.0204964 ],
       [ 0.3429808 , -0.15318486,  0.25303625, -1.28821221, -0.69289057,
        -0.81134119, -0.81807858, -0.27575966],
       [-0.25095213, -1.34247638, -0.98770975,  0.71908574,  0.07120427,
        -0.12597727, -0.676133  , -0.61611067],
       [ 1.82781311, -0.184482  , -3.57259724, -1.28821221, -0.69289057,
         0.41977549, -1.02042653, -0.36084741],
       [-0.54791859,  2.38188392

In [17]:
labels = diabetes_dataset.columns.values
standardize_df = pd.DataFrame(standardize_data,columns=labels[0:8])

In [18]:
standardize_df.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.639947  0.848324       0.149641       0.907270 -0.692891  0.204013   
1    -0.844885 -1.123396      -0.160546       0.530902 -0.692891 -0.684422   
2     1.233880  1.943724      -0.263941      -1.288212 -0.692891 -1.103255   
3    -0.844885 -0.998208      -0.160546       0.154533  0.123302 -0.494043   
4    -1.141852  0.504055      -1.504687       0.907270  0.765836  1.409746   

   DiabetesPedigreeFunction       Age  
0                  0.468492  1.425995  
1                 -0.365061 -0.190672  
2                  0.604397 -0.105584  
3                 -0.920763 -1.041549  
4                  5.484909 -0.020496

In [19]:
X_train,X_test,y_train,y_test = train_test_split(standardize_data,y,test_size=0.2,stratify=y,random_state=2)

In [20]:
print(X_train.shape,X_test.shape)

(614, 8) (154, 8)


# Support Vector Machine Classifier

In [21]:
classifier = svm.SVC(kernel='linear')

In [22]:
classifier.fit(X_train,y_train)

SVC(kernel='linear')

### Predict data on X training 

Accuracy Score

In [23]:
X_train_predict = classifier.predict(X_train)

In [24]:
X_train_predictions_accuracy = accuracy_score(X_train_predict,y_train)

In [25]:
print("Accuracy score for x train data is : ", X_train_predictions_accuracy)

Accuracy score for x train data is :  0.7866449511400652


### Predict data on X test 

In [26]:
X_test_predict = classifier.predict(X_test)
X_test_predictions_accuracy = accuracy_score(X_test_predict,y_test)
print("Accuracy score for x test data is : ", X_test_predictions_accuracy)

Accuracy score for x test data is :  0.7727272727272727


In [27]:
# print(X_test[70:80],y_test[70:80])
test = X_test[51]
out = y_test[51]
print(test,out)

[-0.25095213 -0.77912776 -0.67752325  0.84454186  0.30564246 -0.92556851
  1.4258696   0.49003012] 0


In [28]:
classifier.predict([test])

array([0], dtype=int64)

In [29]:
from sklearn.metrics import classification_report


In [30]:
print(classification_report(X_test_predict,y_test))

              precision    recall  f1-score   support

           0       0.91      0.78      0.84       117
           1       0.52      0.76      0.62        37

    accuracy                           0.77       154
   macro avg       0.71      0.77      0.73       154
weighted avg       0.82      0.77      0.79       154



In [31]:
from sklearn.metrics import confusion_matrix


In [32]:
print(confusion_matrix(X_test_predict,y_test))

[[91 26]
 [ 9 28]]


# KNeighbors Classifier

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
k_neighbors = KNeighborsClassifier()

In [35]:
k_neighbors.fit(X_train,y_train)

KNeighborsClassifier()

### Predict data on X training 

In [36]:
X_train_knn_predicts = k_neighbors.predict(X_train)

In [37]:
X_train_knn_predicts_accuracy = accuracy_score(X_train_knn_predicts,y_train)
print("Accuracy score for x train data is : ", X_train_knn_predicts_accuracy)

Accuracy score for x train data is :  0.8289902280130294


In [38]:
k_neighbors.predict([test])

array([0], dtype=int64)

In [39]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(X_train_knn_predicts,y_train))

[[362  67]
 [ 38 147]]


### Predict data on X test 

In [40]:
X_test_knn_predicts = k_neighbors.predict(X_test)
X_test_knn_predicts_accuracy = accuracy_score(X_test_knn_predicts,y_test)
print("Accuracy score for x test data is : ", X_test_knn_predicts_accuracy)

Accuracy score for x test data is :  0.7207792207792207


In [41]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(X_test_knn_predicts,y_test))

[[87 30]
 [13 24]]


# Linear Regression

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
lineat_regression = LinearRegression()
lineat_regression.fit(X_train,y_train)
X_train_lr_predicts = lineat_regression.predict(X_train)


In [45]:
# X_train_lr_predicts_accuracy = accuracy_score(X_train_lr_predicts,y_train)
# print("Accuracy score for x train data is : ", X_train_lr_predicts_accuracy)
X_train_lr_score = lineat_regression.score(X_train,y_train)
print("Score ",X_train_lr_score)

Score  0.32473331495927626


In [ ]:
X_test_lr_predicts = lineat_regression.predict(X_test)
# X_test_lr_predicts_accuracy = accuracy_score(X_test_lr_predicts,y_test)
# print("Accuracy score for x test data is : ", X_test_lr_predicts_accuracy)

In [46]:
import pickle

In [47]:
pickle.dump(classifier,open('Diabetes_model_svm.pkl','wb'))